### ISSUE TITLE
Cyclic sibling glue example

### ISSUE THREAD

**Issue by shuque** [ietf-wg-dnsop/draft-ietf-dnsop-glue-is-not-optional#14]
From @wessels ..

_COMMENT DW 20210715: This example would be better if it showed a
   cyclic dependency.  As is the foo.test domain can be resolved because
   bar.test doesn't have any other dependencies._

**Comment by moonshiner** [comment]
it also sounds like there should be an invalid example.

**Comment by wessels** [comment]
cyclic sibling glue example was added in 5fe4b072fd1b194707fd3981284fc8dc74e57e20
