### ISSUE TITLE
dig output for "sibling glue" and "cyclic sibling glue" are equivalent

### ISSUE THREAD

**Issue by wessels** [ietf-wg-dnsop/draft-ietf-dnsop-glue-is-not-optional#27]
The sample dig output for the cyclic sibling glue is equivalent to the one for (non-cyclic) sibling blue, just that "foo" and "bar" are reversed.  A single dig output can't really convey the cyclic aspect.  Do we really need it?

**Comment by paulwouters** [comment]
We can make them more different if that's what you prefer to avoid confusion?
I would like to keep it in. So many people didnt get what sibling glue was at first that I think it is good to have the example

**Comment by moonshiner** [comment]
I agree with keeping the example

**Comment by wessels** [comment]
okay, lets leave it then
