### ISSUE TITLE
Set TC=1 only over UDP?

### ISSUE THREAD

**Issue by wessels** [ietf-wg-dnsop/draft-ietf-dnsop-glue-is-not-optional#28]
As currently written the document only talks about setting TC=1 over UDP.  This sort of implies that UDP is the only possible transport where TC flag has meaning.  We don't talk about setting TC over TCP because the assumption is that TCP always has enough room for all glue or whatever.  But this doesn't account for two possibilities

1) a future transport that is limited in space

2) some kind of ridiculous zone configuration with so many NS and glue records that they won't even fit in a single DNS-over-TCP message.

Would it be better to just say "set TC=1 if glue doesn't fit" and not bring UDP or TCP into the requirements language?

**Comment by ableyjoe** [comment]
On Jan 31, 2022, at 21:51, Duane Wessels ***@***.***> wrote:

> Would it be better to just say "set TC=1 if glue doesn't fit" and not bring UDP or TCP into the requirements language?


I like the idea of that, but I think simultaneous possession and ingestion of cake is also possible -- make the general, transport-agnostic point but also give the UDP/TCP fallback as an example that is known to be common at the time of writing.


Joe

**Comment by paulwouters** [comment]
I prefer mentioning UDP and TCP and to say clearly never set it for TCP.  I wouldn't consider "insanely weird" TCP that requires TC=1

**Comment by wessels** [comment]
> I wouldn't consider

would or wouldn't?

**Comment by wessels** [comment]
#29 was merged so closing this for now
