### ISSUE TITLE
Recommendations for when TC=1?

### ISSUE THREAD

**Issue by wessels** [ietf-wg-dnsop/draft-ietf-dnsop-glue-is-not-optional#33]
When a name server sets TC=1 in a response the name server can either leave (a) the records that did fit, or (b) remove all those records and make a minimal sized response.   Currently we don't say anything about leaving or removing records. Should the draft recommend one over the other?

**Comment by ableyjoe** [comment]
On Apr 15, 2022, at 14:45, Duane Wessels ***@***.***> wrote:
> When a name server sets TC=1 in a response the name server can either leave (a) the records that did fit,
> 
RRSets, right? Not RRs. We wouldn't want to infer that it's ok to split RRSets to create a response that fits.
> or (b) remove all those records and make a minimal sized response. Currently we don't say anything about leaving or removing records. Should the draft recommend one over the other?
> 
I don't think it's necessary to say anything about that. I think the adequacy of particular responses to particular queries (the subject of this draft) is orthogonal to the mechanics of truncating any particular response.


Joe
